/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.OpmProducto;
import Transversal.Util;
import java.awt.Point;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author ARISTIZABAL
 */
public class PanelFormularioProducto extends javax.swing.JPanel {

    /**
     * Creates new form PanelFormularioProducto
     */
    public enum Vista {

        Edicion, ConsultaFabrica, ConsultaPuntoVenta, ConsultaCliente
    };

    public PanelFormularioProducto() {
        initComponents();
    }

    public OpmProducto getDatos() {
        OpmProducto producto = new OpmProducto();
        if (!jtfCodigo.getText().isEmpty()) {
            producto.setNmCodigo(Integer.parseInt(jtfCodigo.getText()));
        }
        producto.setNvNombre(jtfNombre.getText());
        producto.setNvDescripcion(jtfDescripcion.getText());
        producto.setNmCostoPp(Double.parseDouble(jtfCostoProduccion.getText()));
        producto.setNmValorPv(Double.parseDouble(jtfCostoVentaPV.getText()));
        producto.setNmValorPm(Double.parseDouble(jtfCostoPorMayor.getText()));
        producto.setNmValorVs(Double.parseDouble(jtfCostoSugerido.getText()));

        producto.setBtActivo(jrbActivo.isSelected());

        return producto;
    }

    public void setDatos(OpmProducto producto) {
        jtfCodigo.setText(producto.getNmCodigo().toString());
        jrbActivo.setSelected(producto.getBtActivo());
        jtfNombre.setText(producto.getNvNombre());
        jtfDescripcion.setText(producto.getNvDescripcion());
        jtfCostoProduccion.setText(producto.getNmCostoPp() + "");
        jtfCostoVentaPV.setText(producto.getNmValorPm() + "");
        jtfCostoPorMayor.setText(producto.getNmCostoPp() + "");
        jtfCostoSugerido.setText(producto.getNmValorVs() + "");
    }

    public boolean validarCamposObligatorios() {
        List<String> campos = new ArrayList<>();
        campos.add(jtfNombre.getText());
        campos.add(jtfCostoProduccion.getText());
        campos.add(jtfCostoVentaPV.getText());
        campos.add(jtfCostoPorMayor.getText());
        campos.add(jtfCostoSugerido.getText());
        return Util.validarCamposObligatorios(campos);
    }

    public int getCodigo() {
        return Integer.parseInt(jtfCodigo.getText());
    }

    public void setVista(Vista v) {
        switch (v) {
            case Edicion:
                break;
            case ConsultaFabrica:
                jrbActivo.setEnabled(false);
                jtfNombre.setEditable(false);
                jtfDescripcion.setEditable(false);
                jtfCostoProduccion.setEditable(false);
                jtfCostoVentaPV.setEditable(false);
                jtfCostoPorMayor.setEditable(false);
                jtfCostoSugerido.setEditable(false);
                break;
            case ConsultaPuntoVenta:
                jrbActivo.setEnabled(false);
                jtfNombre.setEditable(false);
                jtfDescripcion.setEditable(false);
                
                jtfCostoProduccion.setEditable(false);
                jlbCostroProduccion.setVisible(false);
                jtfCostoProduccion.setVisible(false);
                
                jtfCostoVentaPV.setEditable(false);
                jlbCostoVentaPV.setVisible(false);
                jtfCostoVentaPV.setVisible(false);
                
                jtfCostoPorMayor.setEditable(false);
                Point pcpm = jtfCostoPorMayor.getLocation();
                jtfCostoPorMayor.setLocation(pcpm.x,pcpm.y-38);
                Point lpcpm = jlbCostoPorMayor.getLocation();
                jlbCostoPorMayor.setLocation(lpcpm.x,lpcpm.y-38);
                
                jtfCostoSugerido.setEditable(false);
                Point pcs = jtfCostoSugerido.getLocation();
                jtfCostoSugerido.setLocation(pcs.x,pcs.y-38);
                Point lpcs = jlbCostoSugerido.getLocation();
                jlbCostoSugerido.setLocation(lpcs.x,lpcs.y-38);
                repaint();
                break;
            case ConsultaCliente:
                break;
            default:
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jrbActivo = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jtfDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jlbCostoVentaPV = new javax.swing.JLabel();
        jlbCostroProduccion = new javax.swing.JLabel();
        jlbCostoPorMayor = new javax.swing.JLabel();
        jlbCostoSugerido = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JFormattedTextField();
        jtfCostoProduccion = new javax.swing.JTextField();
        jtfCostoVentaPV = new javax.swing.JTextField();
        jtfCostoPorMayor = new javax.swing.JTextField();
        jtfCostoSugerido = new javax.swing.JTextField();

        jLabel1.setText("Codigo");

        jrbActivo.setSelected(true);
        jrbActivo.setText("Activo");

        jLabel2.setText("Nombre(*)");

        jLabel3.setText("Descripcion");

        jlbCostoVentaPV.setText("Costo Venta(*)");

        jlbCostroProduccion.setText("Costo Produccion(*)");

        jlbCostoPorMayor.setText("Costo Por Mayor(*)");

        jlbCostoSugerido.setText("Costo Sugerido(*)");

        jtfCodigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jtfCostoProduccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCostoProduccionKeyTyped(evt);
            }
        });

        jtfCostoVentaPV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCostoVentaPVKeyTyped(evt);
            }
        });

        jtfCostoPorMayor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCostoPorMayorKeyTyped(evt);
            }
        });

        jtfCostoSugerido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCostoSugeridoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(jLabel2))
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jlbCostroProduccion, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jlbCostoPorMayor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfCostoPorMayor)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jtfNombre)
                    .addComponent(jtfCostoProduccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbCostoSugerido, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbCostoVentaPV, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfCostoVentaPV)
                    .addComponent(jrbActivo)
                    .addComponent(jtfDescripcion)
                    .addComponent(jtfCostoSugerido, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jrbActivo)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCostroProduccion)
                    .addComponent(jlbCostoVentaPV)
                    .addComponent(jtfCostoProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCostoVentaPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCostoPorMayor)
                    .addComponent(jlbCostoSugerido)
                    .addComponent(jtfCostoSugerido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCostoPorMayor))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCostoProduccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCostoProduccionKeyTyped
        // TODO add your handling code here:
        if (!Util.validarCampoNumerico(evt, true, jtfCostoProduccion.getText())) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfCostoProduccionKeyTyped

    private void jtfCostoVentaPVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCostoVentaPVKeyTyped
        // TODO add your handling code here:
        if (!Util.validarCampoNumerico(evt, true, jtfCostoVentaPV.getText())) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfCostoVentaPVKeyTyped

    private void jtfCostoPorMayorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCostoPorMayorKeyTyped
        // TODO add your handling code here:
        if (!Util.validarCampoNumerico(evt, true, jtfCostoPorMayor.getText())) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfCostoPorMayorKeyTyped

    private void jtfCostoSugeridoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCostoSugeridoKeyTyped
        // TODO add your handling code here:
        if (!Util.validarCampoNumerico(evt, true, jtfCostoSugerido.getText())) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfCostoSugeridoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jlbCostoPorMayor;
    private javax.swing.JLabel jlbCostoSugerido;
    private javax.swing.JLabel jlbCostoVentaPV;
    private javax.swing.JLabel jlbCostroProduccion;
    private javax.swing.JRadioButton jrbActivo;
    private javax.swing.JFormattedTextField jtfCodigo;
    private javax.swing.JTextField jtfCostoPorMayor;
    private javax.swing.JTextField jtfCostoProduccion;
    private javax.swing.JTextField jtfCostoSugerido;
    private javax.swing.JTextField jtfCostoVentaPV;
    private javax.swing.JTextField jtfDescripcion;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
}
