/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.OpmProducto;
import Transversal.Util;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author ARISTIZABAL
 */
public class PanelFormularioProducto extends javax.swing.JPanel {

    /**
     * Creates new form PanelFormularioProducto
     */
    public PanelFormularioProducto() {
        initComponents();
    }

    public OpmProducto getDatos() {
        OpmProducto producto = new OpmProducto();
        producto.setNvNombre(txfNombre.getText());
        producto.setNvDescripcion(txfDescripcion.getText());
        producto.setNmCosto(Double.parseDouble(txfCosto.getText()));
        producto.setNmValor(Double.parseDouble(txfVenta.getText()));
        producto.setBtActivo(rbtActivo.isSelected());

        return producto;
    }

    public void setDatos(OpmProducto producto) {
        txfCodigo.setText(producto.getNmCodigo().toString());
        rbtActivo.setSelected(producto.getBtActivo());
        txfNombre.setText(producto.getNvNombre());
        txfDescripcion.setText(producto.getNvDescripcion());
        txfCosto.setText(producto.getNmCosto() + "");
        txfVenta.setText(producto.getNmValor() + "");
    }

    public boolean validarCamposObligatorios() {
        List<String> campos = new ArrayList<>();
        campos.add(txfNombre.getText());
        campos.add(txfCosto.getText());
        campos.add(txfVenta.getText());
        return Util.validarCamposObligatorios(campos);
    }

    public int getCodigo() {
        return Integer.parseInt(txfCodigo.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txfCodigo = new javax.swing.JTextField();
        rbtActivo = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txfNombre = new javax.swing.JTextField();
        txfDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txfVenta = new javax.swing.JTextField();
        txfCosto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("Codigo");

        txfCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfCodigoKeyTyped(evt);
            }
        });

        rbtActivo.setSelected(true);
        rbtActivo.setText("Activo");

        jLabel2.setText("Nombre(*)");

        jLabel3.setText("Descripcion");

        jLabel5.setText("Costo Venta(*)");

        txfVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfVentaKeyTyped(evt);
            }
        });

        txfCosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfCostoKeyTyped(evt);
            }
        });

        jLabel4.setText("Costo Produccion(*)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txfNombre)
                    .addComponent(txfCodigo)
                    .addComponent(txfCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtActivo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txfDescripcion)
                    .addComponent(txfVenta))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtActivo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txfVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txfCostoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfCostoKeyTyped
        // TODO add your handling code here:
        if (!Util.validarCampoNumerico(evt, true, txfCosto.getText())) {
            evt.consume();
        }
    }//GEN-LAST:event_txfCostoKeyTyped

    private void txfVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfVentaKeyTyped
        // TODO add your handling code here:
        if (!Util.validarCampoNumerico(evt, true, txfVenta.getText())) {
            evt.consume();
        }
    }//GEN-LAST:event_txfVentaKeyTyped

    private void txfCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfCodigoKeyTyped
        // TODO add your handling code here:
        if (!Util.validarCampoNumerico(evt, false, txfCodigo.getText())) {
            evt.consume();
        }
    }//GEN-LAST:event_txfCodigoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton rbtActivo;
    private javax.swing.JTextField txfCodigo;
    private javax.swing.JTextField txfCosto;
    private javax.swing.JTextField txfDescripcion;
    private javax.swing.JTextField txfNombre;
    private javax.swing.JTextField txfVenta;
    // End of variables declaration//GEN-END:variables
}
