/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ConnectionFactory;
import Controlador.OpmProductoJpaController;
import Controlador.OpmReferenciaProductoJpaController;
import Modelo.OpmProducto;
import Modelo.OpmReferenciaProducto;
import Transversal.Util;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ARISTIZABAL
 */
public class ReferenciaProducto extends javax.swing.JPanel {

    /**
     * Creates new form ReferenciaProducto
     */
    OpmProductoJpaController _jpaControladorProducto;
    OpmReferenciaProductoJpaController _jpaControladorReferencia;
    List<OpmProducto> lsProductos;
    PanelFormularioProducto formularioProducto;
    
    public ReferenciaProducto() {
        _jpaControladorProducto = new OpmProductoJpaController((new ConnectionFactory()).getFactory());
        _jpaControladorReferencia = new OpmReferenciaProductoJpaController((new ConnectionFactory()).getFactory());
        initComponents();
        formularioProducto = new PanelFormularioProducto();
        jpnFormularioProducto.add(formularioProducto);
        formularioProducto.setSize(1100,180);
        formularioProducto.setVisible(true);
        formularioProducto.validate();
        formularioProducto.setVista(PanelFormularioProducto.Vista.ConsultaFabrica);
        inicializarProductos();
        mtdActualizarTabla();
    }
    
    final void inicializarProductos() {
        lsProductos = _jpaControladorProducto.findOpmProductoEntities();
        for (OpmProducto producto : lsProductos) {
            jcbProductos.addItem(producto.getNvNombre());
        }
    }
    
    public boolean validarCamposObligatorios() {
        List<String> campos = new ArrayList<>();
        campos.add(jtfReferencia.getText());
        return Util.validarCamposObligatorios(campos);
    }
    
    OpmReferenciaProducto getDatos(){
        OpmReferenciaProducto referencia = new OpmReferenciaProducto();
        referencia.setNvCodigo(jtfReferencia.getText());
        referencia.setNmProducto(lsProductos.get(jcbProductos.getSelectedIndex()));
        referencia.setNvColor(jtfColor.getText());
        referencia.setNvTalla(jtfTalla.getText());
        referencia.setNvGenero(jcbGenero.getSelectedItem().toString().charAt(0));
        return referencia;
    }
    
     private void mtdActualizarTabla() {
        List<OpmReferenciaProducto> lstReferenciaProductos = _jpaControladorProducto.findOpmProducto(lsProductos.get(jcbProductos.getSelectedIndex()).getNmCodigo()).getOpmReferenciaProductoList();
        if(lstReferenciaProductos == null){
            lstReferenciaProductos =  new ArrayList<>();
        }
        DefaultTableModel modelo = (DefaultTableModel) jtbReferencia.getModel();
        int nroFIlas = modelo.getRowCount();
        for (int i = 0; i < nroFIlas; i++) {
            modelo.removeRow(0);
        }

        for (OpmReferenciaProducto referencia : lstReferenciaProductos) {
            Object[] fila;
            fila = new Object[]{
                referencia.getNvCodigo(),
                referencia.getNmProducto().getNvNombre(),
                referencia.getNvColor(),
                referencia.getNvTalla(),
                referencia.getNvGenero()
            };
            modelo.addRow(fila);
        }
        jtbReferencia.setModel(modelo);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbProductos = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jpnFormularioProducto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbReferencia = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfReferencia = new javax.swing.JTextField();
        jtfColor = new javax.swing.JTextField();
        jtfTalla = new javax.swing.JTextField();
        jcbGenero = new javax.swing.JComboBox();
        jbtRegistrar = new javax.swing.JButton();

        jcbProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbProductosActionPerformed(evt);
            }
        });

        jLabel1.setText("Producto");

        javax.swing.GroupLayout jpnFormularioProductoLayout = new javax.swing.GroupLayout(jpnFormularioProducto);
        jpnFormularioProducto.setLayout(jpnFormularioProductoLayout);
        jpnFormularioProductoLayout.setHorizontalGroup(
            jpnFormularioProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnFormularioProductoLayout.setVerticalGroup(
            jpnFormularioProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        jtbReferencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Referencia", "descripcion", "Color", "Talla", "Genero"
            }
        ));
        jScrollPane1.setViewportView(jtbReferencia);

        jLabel2.setText("Referencia");

        jLabel3.setText("Color");

        jLabel4.setText("Talla");

        jLabel5.setText("Genero");

        jcbGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));

        jbtRegistrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtRegistrar.setText("Registrar");
        jbtRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfReferencia)
                    .addComponent(jtfColor)
                    .addComponent(jtfTalla)
                    .addComponent(jcbGenero, 0, 200, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtRegistrar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfTalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnFormularioProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jcbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnFormularioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcbProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbProductosActionPerformed
        // TODO add your handling code here:
        formularioProducto.setDatos(lsProductos.get(jcbProductos.getSelectedIndex()));
        mtdActualizarTabla();
    }//GEN-LAST:event_jcbProductosActionPerformed

    private void jbtRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRegistrarActionPerformed
        if (validarCamposObligatorios()) {
            try {
                _jpaControladorReferencia.create(getDatos());
                mtdActualizarTabla();
            } catch (Exception ex) {
                Logger.getLogger(ReferenciaProducto.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            
        }
    }//GEN-LAST:event_jbtRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtRegistrar;
    private javax.swing.JComboBox jcbGenero;
    private javax.swing.JComboBox jcbProductos;
    private javax.swing.JPanel jpnFormularioProducto;
    private javax.swing.JTable jtbReferencia;
    private javax.swing.JTextField jtfColor;
    private javax.swing.JTextField jtfReferencia;
    private javax.swing.JTextField jtfTalla;
    // End of variables declaration//GEN-END:variables
}
